
package employee_ms.view;

import employee_ms.view.panels.Dashboard;
import employee_ms.view.panels.Request_Leave;
import employee_ms.view.panels.View_Schedule;
import employee_ms.view.panels.View_Attendance;
import employee_ms.view.panels.Employee;
import employee_ms.view.panels.Payroll_Process;
import employee_ms.view.panels.Login_Form;



public class Admin_dashboard extends javax.swing.JFrame {

    
    private final Dashboard dashboardPanel;
    
    /**
     * Creates new form admin_dashboard
     */
    public Admin_dashboard() {
        initComponents();
        dashboardPanel = new Dashboard();
        jPanel2.add(dashboardPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        btn_Employee = new javax.swing.JButton();
        btn_Salary = new javax.swing.JButton();
        btn_Dashborad = new javax.swing.JButton();
        btn_Leave = new javax.swing.JButton();
        btn_Help = new javax.swing.JButton();
        btn_Logout = new javax.swing.JButton();
        btn_Report = new javax.swing.JButton();
        btn_Schedule = new javax.swing.JButton();
        btn_Attendance = new javax.swing.JButton();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btn_Search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Employee.setBackground(new java.awt.Color(0, 0, 102));
        btn_Employee.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Employee.setForeground(new java.awt.Color(255, 255, 255));
        btn_Employee.setText("Employee");
        btn_Employee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Employee.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Employee.setMargin(new java.awt.Insets(2, 50, 3, 14));
        btn_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmployeeActionPerformed(evt);
            }
        });
        jPanel5.add(btn_Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 246, 39));

        btn_Salary.setBackground(new java.awt.Color(0, 0, 102));
        btn_Salary.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Salary.setForeground(new java.awt.Color(255, 255, 255));
        btn_Salary.setText("Salary");
        btn_Salary.setAlignmentY(0.9F);
        btn_Salary.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Salary.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Salary.setMargin(new java.awt.Insets(2, 50, 3, 14));
        btn_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalaryActionPerformed(evt);
            }
        });
        jPanel5.add(btn_Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 285, 246, 39));

        btn_Dashborad.setBackground(new java.awt.Color(0, 0, 102));
        btn_Dashborad.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Dashborad.setForeground(new java.awt.Color(255, 255, 255));
        btn_Dashborad.setText("Dashboard");
        btn_Dashborad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Dashborad.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Dashborad.setMargin(new java.awt.Insets(2, 50, 3, 14));
        btn_Dashborad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DashboradActionPerformed(evt);
            }
        });
        jPanel5.add(btn_Dashborad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 250, 39));

        btn_Leave.setBackground(new java.awt.Color(0, 0, 102));
        btn_Leave.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Leave.setForeground(new java.awt.Color(255, 255, 255));
        btn_Leave.setText("Leave");
        btn_Leave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Leave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Leave.setMargin(new java.awt.Insets(2, 50, 3, 14));
        btn_Leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LeaveActionPerformed(evt);
            }
        });
        jPanel5.add(btn_Leave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 246, 39));

        btn_Help.setBackground(new java.awt.Color(0, 0, 102));
        btn_Help.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Help.setForeground(new java.awt.Color(255, 255, 255));
        btn_Help.setText("Help ?");
        btn_Help.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Help.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Help.setMargin(new java.awt.Insets(2, 50, 3, 14));
        btn_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HelpActionPerformed(evt);
            }
        });
        jPanel5.add(btn_Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 246, 39));

        btn_Logout.setBackground(new java.awt.Color(0, 0, 102));
        btn_Logout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_Logout.setText("Log out");
        btn_Logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Logout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Logout.setMargin(new java.awt.Insets(2, 50, 3, 14));
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });
        jPanel5.add(btn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 555, 246, 39));

        btn_Report.setBackground(new java.awt.Color(0, 0, 102));
        btn_Report.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Report.setForeground(new java.awt.Color(255, 255, 255));
        btn_Report.setText("Report ");
        btn_Report.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Report.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Report.setMargin(new java.awt.Insets(2, 50, 3, 14));
        btn_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReportActionPerformed(evt);
            }
        });
        jPanel5.add(btn_Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 465, 246, 39));

        btn_Schedule.setBackground(new java.awt.Color(0, 0, 102));
        btn_Schedule.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Schedule.setForeground(new java.awt.Color(255, 255, 255));
        btn_Schedule.setText("Schedule");
        btn_Schedule.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Schedule.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Schedule.setMargin(new java.awt.Insets(2, 50, 3, 14));
        btn_Schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ScheduleActionPerformed(evt);
            }
        });
        jPanel5.add(btn_Schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 246, 39));

        btn_Attendance.setBackground(new java.awt.Color(0, 0, 102));
        btn_Attendance.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_Attendance.setForeground(new java.awt.Color(255, 255, 255));
        btn_Attendance.setText("Attendance");
        btn_Attendance.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Attendance.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Attendance.setMargin(new java.awt.Insets(2, 50, 3, 14));
        btn_Attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AttendanceActionPerformed(evt);
            }
        });
        jPanel5.add(btn_Attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 375, 246, 39));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Java\\Employee_MS\\src\\employee_ms\\OIP copy.png")); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        jPanel5.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 15, -1, -1));

        jPanel4.setBackground(new java.awt.Color(187, 226, 244));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("First Name");
        jLabel3.setToolTipText("");

        txtSearch.setEditable(false);
        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setText("Search");

        btn_Search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Search.setText("Search");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("ArchiTech CAD \nAcademy");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch)
                        .addComponent(btn_Search)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmployeeActionPerformed
      Employee obj = new Employee();
        jPanel5.add(obj);
        
    }//GEN-LAST:event_btn_EmployeeActionPerformed

    private void btn_SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalaryActionPerformed
    Payroll_Process obj = new Payroll_Process();
        jPanel5.add(obj);
    }//GEN-LAST:event_btn_SalaryActionPerformed

    private void btn_DashboradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DashboradActionPerformed
    Dashboard obj = new Dashboard();
    jPanel5.add(obj);
    }//GEN-LAST:event_btn_DashboradActionPerformed

    private void btn_LeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LeaveActionPerformed
    Request_Leave obj = new Request_Leave();
        jPanel5.add(obj);
    }//GEN-LAST:event_btn_LeaveActionPerformed

    private void btn_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HelpActionPerformed

    }//GEN-LAST:event_btn_HelpActionPerformed

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
     Login_Form obj = new Login_Form();
        obj.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void btn_ScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ScheduleActionPerformed
      View_Schedule obj = new View_Schedule();
        jPanel5.add(obj);
    }//GEN-LAST:event_btn_ScheduleActionPerformed

    private void btn_AttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AttendanceActionPerformed
     View_Attendance obj = new View_Attendance();
        jPanel5.add(obj);
    }//GEN-LAST:event_btn_AttendanceActionPerformed

    private void btn_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReportActionPerformed
    
    }//GEN-LAST:event_btn_ReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Attendance;
    private javax.swing.JButton btn_Dashborad;
    private javax.swing.JButton btn_Employee;
    private javax.swing.JButton btn_Help;
    private javax.swing.JButton btn_Leave;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_Report;
    private javax.swing.JButton btn_Salary;
    private javax.swing.JButton btn_Schedule;
    private javax.swing.JButton btn_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private rojerusan.RSPanelImage rSPanelImage1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
