/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee_ms.view;

/**
 *
 * @author User
 */
public class View_payroll extends javax.swing.JFrame {

    /**
     * Creates new form View_payroll
     */
    public View_payroll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CreateEmployeePanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txt_Employee_ID = new javax.swing.JTextField();
        txt_Employee_Name = new javax.swing.JTextField();
        txt_Employee_Type = new javax.swing.JTextField();
        txt_Total_Salary = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_Month = new javax.swing.JTextField();
        txt_Year = new javax.swing.JTextField();
        txt_Basic_Salary = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txt_Hour_Rate = new javax.swing.JTextField();
        txt_Working_Days = new javax.swing.JTextField();
        txt_OT_Hours = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txt_Tax_Amount = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        btnCalculate1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        txt_Incentive = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txt_ETF = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txt_EPF = new javax.swing.JTextField();
        CreateEmployeePanel2 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txt_Employee_ID1 = new javax.swing.JTextField();
        txt_Employee_Name1 = new javax.swing.JTextField();
        txt_Employee_Type1 = new javax.swing.JTextField();
        txt_Total_Salary1 = new javax.swing.JTextField();
        btnCalculate2 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txt_Month1 = new javax.swing.JTextField();
        txt_Year1 = new javax.swing.JTextField();
        txt_Basic_Salary1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        txt_Hour_Rate1 = new javax.swing.JTextField();
        txt_Working_Days1 = new javax.swing.JTextField();
        txt_OT_Hours1 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txt_Tax_Amount1 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        btnCalculate3 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        txt_Incentive1 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        txt_ETF1 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        txt_EPF1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        CreateEmployeePanel3 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        txt_Employee_ID2 = new javax.swing.JTextField();
        txt_Employee_Name2 = new javax.swing.JTextField();
        txt_Employee_Type2 = new javax.swing.JTextField();
        txt_Total_Salary2 = new javax.swing.JTextField();
        btnCalculate4 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        txt_Month2 = new javax.swing.JTextField();
        txt_Year2 = new javax.swing.JTextField();
        txt_Basic_Salary2 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        txt_Hour_Rate2 = new javax.swing.JTextField();
        txt_Working_Days2 = new javax.swing.JTextField();
        txt_OT_Hours2 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        txt_Tax_Amount2 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        btnCalculate5 = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        txt_Incentive2 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        txt_ETF2 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        txt_EPF2 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateEmployeePanel1.setBackground(new java.awt.Color(0, 0, 102));
        CreateEmployeePanel1.setLayout(null);

        jLabel26.setBackground(new java.awt.Color(0, 0, 204));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Employee ID");
        CreateEmployeePanel1.add(jLabel26);
        jLabel26.setBounds(20, 30, 144, 25);

        jLabel27.setBackground(new java.awt.Color(0, 0, 204));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Employee Name");
        CreateEmployeePanel1.add(jLabel27);
        jLabel27.setBounds(20, 60, 144, 25);

        jLabel28.setBackground(new java.awt.Color(0, 0, 204));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Position");
        CreateEmployeePanel1.add(jLabel28);
        jLabel28.setBounds(20, 90, 144, 25);

        jLabel29.setBackground(new java.awt.Color(0, 0, 204));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Month");
        CreateEmployeePanel1.add(jLabel29);
        jLabel29.setBounds(20, 120, 144, 25);

        jLabel32.setBackground(new java.awt.Color(0, 0, 204));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Gross Salary");
        CreateEmployeePanel1.add(jLabel32);
        jLabel32.setBounds(20, 180, 144, 25);

        jLabel33.setBackground(new java.awt.Color(0, 0, 204));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Hour Rate");
        CreateEmployeePanel1.add(jLabel33);
        jLabel33.setBounds(57, 338, 144, 25);

        txt_Employee_ID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Employee_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Employee_IDActionPerformed(evt);
            }
        });
        CreateEmployeePanel1.add(txt_Employee_ID);
        txt_Employee_ID.setBounds(260, 30, 213, 26);

        txt_Employee_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel1.add(txt_Employee_Name);
        txt_Employee_Name.setBounds(260, 60, 213, 26);

        txt_Employee_Type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel1.add(txt_Employee_Type);
        txt_Employee_Type.setBounds(260, 90, 213, 26);

        txt_Total_Salary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel1.add(txt_Total_Salary);
        txt_Total_Salary.setBounds(260, 480, 213, 26);

        btnCalculate.setBackground(new java.awt.Color(0, 0, 204));
        btnCalculate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 0));
        btnCalculate.setText("Calculate");
        btnCalculate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        CreateEmployeePanel1.add(btnCalculate);
        btnCalculate.setBounds(260, 520, 100, 30);

        jLabel34.setBackground(new java.awt.Color(0, 0, 204));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Bonus");
        CreateEmployeePanel1.add(jLabel34);
        jLabel34.setBounds(20, 210, 144, 25);

        jLabel35.setBackground(new java.awt.Color(0, 0, 204));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Time Worked");
        CreateEmployeePanel1.add(jLabel35);
        jLabel35.setBounds(20, 250, 144, 25);

        jLabel36.setBackground(new java.awt.Color(0, 0, 204));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Working Days");
        CreateEmployeePanel1.add(jLabel36);
        jLabel36.setBounds(57, 275, 144, 25);

        txt_Month.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel1.add(txt_Month);
        txt_Month.setBounds(260, 120, 213, 26);

        txt_Year.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel1.add(txt_Year);
        txt_Year.setBounds(260, 150, 213, 26);

        txt_Basic_Salary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel1.add(txt_Basic_Salary);
        txt_Basic_Salary.setBounds(260, 180, 213, 26);

        jLabel37.setBackground(new java.awt.Color(0, 0, 204));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("OT Houres");
        CreateEmployeePanel1.add(jLabel37);
        jLabel37.setBounds(57, 309, 144, 25);

        txt_Hour_Rate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel1.add(txt_Hour_Rate);
        txt_Hour_Rate.setBounds(260, 340, 141, 26);

        txt_Working_Days.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel1.add(txt_Working_Days);
        txt_Working_Days.setBounds(260, 280, 141, 26);

        txt_OT_Hours.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel1.add(txt_OT_Hours);
        txt_OT_Hours.setBounds(260, 310, 141, 26);

        jLabel38.setBackground(new java.awt.Color(0, 0, 204));
        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("ETF");
        CreateEmployeePanel1.add(jLabel38);
        jLabel38.setBounds(20, 380, 144, 25);

        txt_Tax_Amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel1.add(txt_Tax_Amount);
        txt_Tax_Amount.setBounds(260, 430, 213, 26);

        jLabel39.setBackground(new java.awt.Color(0, 0, 204));
        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Total Salary");
        CreateEmployeePanel1.add(jLabel39);
        jLabel39.setBounds(10, 470, 225, 40);

        btnCalculate1.setBackground(new java.awt.Color(0, 0, 204));
        btnCalculate1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalculate1.setForeground(new java.awt.Color(255, 255, 0));
        btnCalculate1.setText("Clear");
        btnCalculate1.setActionCommand("cLEAR");
        btnCalculate1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalculate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate1ActionPerformed(evt);
            }
        });
        CreateEmployeePanel1.add(btnCalculate1);
        btnCalculate1.setBounds(390, 520, 90, 30);

        jLabel30.setBackground(new java.awt.Color(0, 0, 204));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Year");
        CreateEmployeePanel1.add(jLabel30);
        jLabel30.setBounds(20, 150, 144, 25);

        txt_Incentive.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel1.add(txt_Incentive);
        txt_Incentive.setBounds(260, 210, 213, 26);

        jLabel40.setBackground(new java.awt.Color(0, 0, 204));
        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("EPF");
        CreateEmployeePanel1.add(jLabel40);
        jLabel40.setBounds(20, 400, 144, 25);

        txt_ETF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel1.add(txt_ETF);
        txt_ETF.setBounds(260, 370, 213, 26);

        jLabel41.setBackground(new java.awt.Color(0, 0, 204));
        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Tax Amount");
        CreateEmployeePanel1.add(jLabel41);
        jLabel41.setBounds(20, 420, 144, 25);

        txt_EPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel1.add(txt_EPF);
        txt_EPF.setBounds(260, 400, 213, 26);

        getContentPane().add(CreateEmployeePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        CreateEmployeePanel2.setBackground(new java.awt.Color(0, 0, 102));
        CreateEmployeePanel2.setLayout(null);

        jLabel31.setBackground(new java.awt.Color(0, 0, 204));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Employee ID");
        CreateEmployeePanel2.add(jLabel31);
        jLabel31.setBounds(20, 30, 144, 25);

        jLabel42.setBackground(new java.awt.Color(0, 0, 204));
        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Employee Name");
        CreateEmployeePanel2.add(jLabel42);
        jLabel42.setBounds(20, 60, 144, 25);

        jLabel43.setBackground(new java.awt.Color(0, 0, 204));
        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Position");
        CreateEmployeePanel2.add(jLabel43);
        jLabel43.setBounds(20, 90, 144, 25);

        jLabel44.setBackground(new java.awt.Color(0, 0, 204));
        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Month");
        CreateEmployeePanel2.add(jLabel44);
        jLabel44.setBounds(20, 120, 144, 25);

        jLabel45.setBackground(new java.awt.Color(0, 0, 204));
        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Gross Salary");
        CreateEmployeePanel2.add(jLabel45);
        jLabel45.setBounds(20, 180, 144, 25);

        jLabel46.setBackground(new java.awt.Color(0, 0, 204));
        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Hour Rate");
        CreateEmployeePanel2.add(jLabel46);
        jLabel46.setBounds(57, 338, 144, 25);

        txt_Employee_ID1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Employee_ID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Employee_ID1ActionPerformed(evt);
            }
        });
        CreateEmployeePanel2.add(txt_Employee_ID1);
        txt_Employee_ID1.setBounds(260, 30, 213, 26);

        txt_Employee_Name1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel2.add(txt_Employee_Name1);
        txt_Employee_Name1.setBounds(260, 60, 213, 26);

        txt_Employee_Type1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel2.add(txt_Employee_Type1);
        txt_Employee_Type1.setBounds(260, 90, 213, 26);

        txt_Total_Salary1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel2.add(txt_Total_Salary1);
        txt_Total_Salary1.setBounds(260, 480, 213, 26);

        btnCalculate2.setBackground(new java.awt.Color(0, 0, 204));
        btnCalculate2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalculate2.setForeground(new java.awt.Color(255, 255, 0));
        btnCalculate2.setText("Calculate");
        btnCalculate2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalculate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate2ActionPerformed(evt);
            }
        });
        CreateEmployeePanel2.add(btnCalculate2);
        btnCalculate2.setBounds(260, 520, 100, 30);

        jLabel47.setBackground(new java.awt.Color(0, 0, 204));
        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Bonus");
        CreateEmployeePanel2.add(jLabel47);
        jLabel47.setBounds(20, 210, 144, 25);

        jLabel48.setBackground(new java.awt.Color(0, 0, 204));
        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Time Worked");
        CreateEmployeePanel2.add(jLabel48);
        jLabel48.setBounds(20, 250, 144, 25);

        jLabel49.setBackground(new java.awt.Color(0, 0, 204));
        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Working Days");
        CreateEmployeePanel2.add(jLabel49);
        jLabel49.setBounds(57, 275, 144, 25);

        txt_Month1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel2.add(txt_Month1);
        txt_Month1.setBounds(260, 120, 213, 26);

        txt_Year1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel2.add(txt_Year1);
        txt_Year1.setBounds(260, 150, 213, 26);

        txt_Basic_Salary1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel2.add(txt_Basic_Salary1);
        txt_Basic_Salary1.setBounds(260, 180, 213, 26);

        jLabel50.setBackground(new java.awt.Color(0, 0, 204));
        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("OT Houres");
        CreateEmployeePanel2.add(jLabel50);
        jLabel50.setBounds(57, 309, 144, 25);

        txt_Hour_Rate1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel2.add(txt_Hour_Rate1);
        txt_Hour_Rate1.setBounds(260, 340, 141, 26);

        txt_Working_Days1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel2.add(txt_Working_Days1);
        txt_Working_Days1.setBounds(260, 280, 141, 26);

        txt_OT_Hours1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel2.add(txt_OT_Hours1);
        txt_OT_Hours1.setBounds(260, 310, 141, 26);

        jLabel51.setBackground(new java.awt.Color(0, 0, 204));
        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("ETF");
        CreateEmployeePanel2.add(jLabel51);
        jLabel51.setBounds(20, 380, 144, 25);

        txt_Tax_Amount1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel2.add(txt_Tax_Amount1);
        txt_Tax_Amount1.setBounds(260, 430, 213, 26);

        jLabel52.setBackground(new java.awt.Color(0, 0, 204));
        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Total Salary");
        CreateEmployeePanel2.add(jLabel52);
        jLabel52.setBounds(10, 470, 225, 40);

        btnCalculate3.setBackground(new java.awt.Color(0, 0, 204));
        btnCalculate3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalculate3.setForeground(new java.awt.Color(255, 255, 0));
        btnCalculate3.setText("Clear");
        btnCalculate3.setActionCommand("cLEAR");
        btnCalculate3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalculate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate3ActionPerformed(evt);
            }
        });
        CreateEmployeePanel2.add(btnCalculate3);
        btnCalculate3.setBounds(390, 520, 90, 30);

        jLabel53.setBackground(new java.awt.Color(0, 0, 204));
        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Year");
        CreateEmployeePanel2.add(jLabel53);
        jLabel53.setBounds(20, 150, 144, 25);

        txt_Incentive1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel2.add(txt_Incentive1);
        txt_Incentive1.setBounds(260, 210, 213, 26);

        jLabel54.setBackground(new java.awt.Color(0, 0, 204));
        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("EPF");
        CreateEmployeePanel2.add(jLabel54);
        jLabel54.setBounds(20, 400, 144, 25);

        txt_ETF1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel2.add(txt_ETF1);
        txt_ETF1.setBounds(260, 370, 213, 26);

        jLabel55.setBackground(new java.awt.Color(0, 0, 204));
        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Tax Amount");
        CreateEmployeePanel2.add(jLabel55);
        jLabel55.setBounds(20, 420, 144, 25);

        txt_EPF1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel2.add(txt_EPF1);
        txt_EPF1.setBounds(260, 400, 213, 26);

        getContentPane().add(CreateEmployeePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        CreateEmployeePanel3.setBackground(new java.awt.Color(0, 0, 102));
        CreateEmployeePanel3.setLayout(null);

        jLabel56.setBackground(new java.awt.Color(0, 0, 204));
        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Employee ID");
        CreateEmployeePanel3.add(jLabel56);
        jLabel56.setBounds(20, 30, 144, 25);

        jLabel57.setBackground(new java.awt.Color(0, 0, 204));
        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Employee Name");
        CreateEmployeePanel3.add(jLabel57);
        jLabel57.setBounds(20, 60, 144, 25);

        jLabel58.setBackground(new java.awt.Color(0, 0, 204));
        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Position");
        CreateEmployeePanel3.add(jLabel58);
        jLabel58.setBounds(20, 90, 144, 25);

        jLabel59.setBackground(new java.awt.Color(0, 0, 204));
        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Month");
        CreateEmployeePanel3.add(jLabel59);
        jLabel59.setBounds(20, 120, 144, 25);

        jLabel60.setBackground(new java.awt.Color(0, 0, 204));
        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Gross Salary");
        CreateEmployeePanel3.add(jLabel60);
        jLabel60.setBounds(20, 180, 144, 25);

        jLabel61.setBackground(new java.awt.Color(0, 0, 204));
        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Hour Rate");
        CreateEmployeePanel3.add(jLabel61);
        jLabel61.setBounds(80, 370, 144, 25);

        txt_Employee_ID2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Employee_ID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Employee_ID2ActionPerformed(evt);
            }
        });
        CreateEmployeePanel3.add(txt_Employee_ID2);
        txt_Employee_ID2.setBounds(260, 30, 213, 26);

        txt_Employee_Name2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel3.add(txt_Employee_Name2);
        txt_Employee_Name2.setBounds(260, 60, 213, 26);

        txt_Employee_Type2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel3.add(txt_Employee_Type2);
        txt_Employee_Type2.setBounds(260, 90, 213, 26);

        txt_Total_Salary2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel3.add(txt_Total_Salary2);
        txt_Total_Salary2.setBounds(260, 560, 213, 26);

        btnCalculate4.setBackground(new java.awt.Color(0, 0, 204));
        btnCalculate4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalculate4.setForeground(new java.awt.Color(255, 255, 0));
        btnCalculate4.setText("View");
        btnCalculate4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalculate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate4ActionPerformed(evt);
            }
        });
        CreateEmployeePanel3.add(btnCalculate4);
        btnCalculate4.setBounds(260, 610, 100, 30);

        jLabel62.setBackground(new java.awt.Color(0, 0, 204));
        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Bonus");
        CreateEmployeePanel3.add(jLabel62);
        jLabel62.setBounds(20, 210, 144, 25);

        jLabel63.setBackground(new java.awt.Color(0, 0, 204));
        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Time Worked");
        CreateEmployeePanel3.add(jLabel63);
        jLabel63.setBounds(20, 260, 144, 25);

        jLabel64.setBackground(new java.awt.Color(0, 0, 204));
        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Working Days");
        CreateEmployeePanel3.add(jLabel64);
        jLabel64.setBounds(70, 290, 144, 25);

        txt_Month2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel3.add(txt_Month2);
        txt_Month2.setBounds(260, 120, 213, 26);

        txt_Year2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel3.add(txt_Year2);
        txt_Year2.setBounds(260, 150, 213, 26);

        txt_Basic_Salary2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel3.add(txt_Basic_Salary2);
        txt_Basic_Salary2.setBounds(260, 180, 213, 26);

        jLabel65.setBackground(new java.awt.Color(0, 0, 204));
        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("OT Houres");
        CreateEmployeePanel3.add(jLabel65);
        jLabel65.setBounds(80, 330, 144, 25);

        txt_Hour_Rate2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel3.add(txt_Hour_Rate2);
        txt_Hour_Rate2.setBounds(260, 370, 141, 26);

        txt_Working_Days2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel3.add(txt_Working_Days2);
        txt_Working_Days2.setBounds(260, 290, 141, 26);

        txt_OT_Hours2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel3.add(txt_OT_Hours2);
        txt_OT_Hours2.setBounds(260, 330, 141, 26);

        jLabel66.setBackground(new java.awt.Color(0, 0, 204));
        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("ETF");
        CreateEmployeePanel3.add(jLabel66);
        jLabel66.setBounds(20, 420, 144, 25);

        txt_Tax_Amount2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel3.add(txt_Tax_Amount2);
        txt_Tax_Amount2.setBounds(260, 500, 213, 26);

        jLabel67.setBackground(new java.awt.Color(0, 0, 204));
        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Total Salary");
        CreateEmployeePanel3.add(jLabel67);
        jLabel67.setBounds(20, 550, 225, 40);

        btnCalculate5.setBackground(new java.awt.Color(0, 0, 204));
        btnCalculate5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalculate5.setForeground(new java.awt.Color(255, 255, 0));
        btnCalculate5.setText("Clear");
        btnCalculate5.setActionCommand("cLEAR");
        btnCalculate5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalculate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate5ActionPerformed(evt);
            }
        });
        CreateEmployeePanel3.add(btnCalculate5);
        btnCalculate5.setBounds(400, 610, 90, 30);

        jLabel68.setBackground(new java.awt.Color(0, 0, 204));
        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Year");
        CreateEmployeePanel3.add(jLabel68);
        jLabel68.setBounds(20, 150, 144, 25);

        txt_Incentive2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel3.add(txt_Incentive2);
        txt_Incentive2.setBounds(260, 210, 213, 26);

        jLabel69.setBackground(new java.awt.Color(0, 0, 204));
        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("EPF");
        CreateEmployeePanel3.add(jLabel69);
        jLabel69.setBounds(20, 460, 144, 25);

        txt_ETF2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel3.add(txt_ETF2);
        txt_ETF2.setBounds(260, 420, 213, 26);

        jLabel70.setBackground(new java.awt.Color(0, 0, 204));
        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Tax Amount");
        CreateEmployeePanel3.add(jLabel70);
        jLabel70.setBounds(20, 500, 144, 25);

        txt_EPF2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeePanel3.add(txt_EPF2);
        txt_EPF2.setBounds(260, 460, 213, 26);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(CreateEmployeePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(CreateEmployeePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Employee_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Employee_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Employee_IDActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        double basicSalary;
        double incentive;
        double workingDays;
        double hours;
        double hourRate;
        double etf;
        double EPF;
        double TaxAmount;
        double totalSalary;

        basicSalary = Double.valueOf(txt_Basic_Salary.getText());
        incentive = Double.parseDouble(txt_Incentive.getText());
        workingDays =  Double.parseDouble(txt_Working_Days.getText());
        hours = Double.parseDouble(txt_OT_Hours.getText());
        hourRate  = Double.parseDouble(txt_Hour_Rate.getText());
        etf  = Double.parseDouble(txt_ETF.getText());
        EPF = Double.parseDouble(txt_EPF.getText());
        TaxAmount  = Double.parseDouble(txt_Tax_Amount.getText());
        totalSalary = Double.parseDouble(txt_Total_Salary.getText());
        if(basicSalary>100000){
            txt_Tax_Amount.setVisible(true);
            totalSalary = basicSalary + incentive - (etf+EPF+TaxAmount) + (workingDays * hourRate * hours);
        }
        else{
            txt_Tax_Amount.setVisible(false);
            totalSalary  = basicSalary + incentive - (etf+EPF) + (workingDays * hourRate * hours);
        }

        String totSal = Double.toString(totalSalary);
        txt_Total_Salary.setText(totSal);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnCalculate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculate1ActionPerformed

    private void txt_Employee_ID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Employee_ID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Employee_ID1ActionPerformed

    private void btnCalculate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate2ActionPerformed
        double basicSalary;
        double incentive;
        double workingDays;
        double hours;
        double hourRate;
        double etf;
        double EPF;
        double TaxAmount;
        double totalSalary;

        basicSalary = Double.valueOf(txt_Basic_Salary.getText());
        incentive = Double.parseDouble(txt_Incentive.getText());
        workingDays =  Double.parseDouble(txt_Working_Days.getText());
        hours = Double.parseDouble(txt_OT_Hours.getText());
        hourRate  = Double.parseDouble(txt_Hour_Rate.getText());
        etf  = Double.parseDouble(txt_ETF.getText());
        EPF = Double.parseDouble(txt_EPF.getText());
        TaxAmount  = Double.parseDouble(txt_Tax_Amount.getText());
        totalSalary = Double.parseDouble(txt_Total_Salary.getText());
        if(basicSalary>100000){
            txt_Tax_Amount.setVisible(true);
            totalSalary = basicSalary + incentive - (etf+EPF+TaxAmount) + (workingDays * hourRate * hours);
        }
        else{
            txt_Tax_Amount.setVisible(false);
            totalSalary  = basicSalary + incentive - (etf+EPF) + (workingDays * hourRate * hours);
        }

        String totSal = Double.toString(totalSalary);
        txt_Total_Salary.setText(totSal);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculate2ActionPerformed

    private void btnCalculate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculate3ActionPerformed

    private void txt_Employee_ID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Employee_ID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Employee_ID2ActionPerformed

    private void btnCalculate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate4ActionPerformed
        double basicSalary;
        double incentive;
        double workingDays;
        double hours;
        double hourRate;
        double etf;
        double EPF;
        double TaxAmount;
        double totalSalary;

        basicSalary = Double.valueOf(txt_Basic_Salary.getText());
        incentive = Double.parseDouble(txt_Incentive.getText());
        workingDays =  Double.parseDouble(txt_Working_Days.getText());
        hours = Double.parseDouble(txt_OT_Hours.getText());
        hourRate  = Double.parseDouble(txt_Hour_Rate.getText());
        etf  = Double.parseDouble(txt_ETF.getText());
        EPF = Double.parseDouble(txt_EPF.getText());
        TaxAmount  = Double.parseDouble(txt_Tax_Amount.getText());
        totalSalary = Double.parseDouble(txt_Total_Salary.getText());
        if(basicSalary>100000){
            txt_Tax_Amount.setVisible(true);
            totalSalary = basicSalary + incentive - (etf+EPF+TaxAmount) + (workingDays * hourRate * hours);
        }
        else{
            txt_Tax_Amount.setVisible(false);
            totalSalary  = basicSalary + incentive - (etf+EPF) + (workingDays * hourRate * hours);
        }

        String totSal = Double.toString(totalSalary);
        txt_Total_Salary.setText(totSal);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculate4ActionPerformed

    private void btnCalculate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculate5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_payroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateEmployeePanel1;
    private javax.swing.JPanel CreateEmployeePanel2;
    private javax.swing.JPanel CreateEmployeePanel3;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCalculate1;
    private javax.swing.JButton btnCalculate2;
    private javax.swing.JButton btnCalculate3;
    private javax.swing.JButton btnCalculate4;
    private javax.swing.JButton btnCalculate5;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_Basic_Salary;
    private javax.swing.JTextField txt_Basic_Salary1;
    private javax.swing.JTextField txt_Basic_Salary2;
    private javax.swing.JTextField txt_EPF;
    private javax.swing.JTextField txt_EPF1;
    private javax.swing.JTextField txt_EPF2;
    private javax.swing.JTextField txt_ETF;
    private javax.swing.JTextField txt_ETF1;
    private javax.swing.JTextField txt_ETF2;
    private javax.swing.JTextField txt_Employee_ID;
    private javax.swing.JTextField txt_Employee_ID1;
    private javax.swing.JTextField txt_Employee_ID2;
    private javax.swing.JTextField txt_Employee_Name;
    private javax.swing.JTextField txt_Employee_Name1;
    private javax.swing.JTextField txt_Employee_Name2;
    private javax.swing.JTextField txt_Employee_Type;
    private javax.swing.JTextField txt_Employee_Type1;
    private javax.swing.JTextField txt_Employee_Type2;
    private javax.swing.JTextField txt_Hour_Rate;
    private javax.swing.JTextField txt_Hour_Rate1;
    private javax.swing.JTextField txt_Hour_Rate2;
    private javax.swing.JTextField txt_Incentive;
    private javax.swing.JTextField txt_Incentive1;
    private javax.swing.JTextField txt_Incentive2;
    private javax.swing.JTextField txt_Month;
    private javax.swing.JTextField txt_Month1;
    private javax.swing.JTextField txt_Month2;
    private javax.swing.JTextField txt_OT_Hours;
    private javax.swing.JTextField txt_OT_Hours1;
    private javax.swing.JTextField txt_OT_Hours2;
    private javax.swing.JTextField txt_Tax_Amount;
    private javax.swing.JTextField txt_Tax_Amount1;
    private javax.swing.JTextField txt_Tax_Amount2;
    private javax.swing.JTextField txt_Total_Salary;
    private javax.swing.JTextField txt_Total_Salary1;
    private javax.swing.JTextField txt_Total_Salary2;
    private javax.swing.JTextField txt_Working_Days;
    private javax.swing.JTextField txt_Working_Days1;
    private javax.swing.JTextField txt_Working_Days2;
    private javax.swing.JTextField txt_Year;
    private javax.swing.JTextField txt_Year1;
    private javax.swing.JTextField txt_Year2;
    // End of variables declaration//GEN-END:variables
}
